from typing import final

def normalize(input: str) -> str: ...
def matches(a: str, b: str) -> bool: ...
def similarity_score(a: str, b: str) -> float: ...
def normalize_batch(inputs: list[str]) -> list[str]: ...

@final
class SearchHit:
    original: str
    score: float

@final
class Index:
    def __init__(self, corpus: list[str]) -> None: ...
    def search(self, query: str, threshold: float) -> list[SearchHit]: ...
    def __repr__(self) -> str: ...

@final
class Normalizer:
    def __init__(self, strip_ivs: bool = ..., fold_variants: bool = ...,
                 width_normalization: bool = ..., case_fold: bool = ...,
                 kana_to_katakana: bool = ..., kana_to_hiragana: bool = ...) -> None: ...
    def normalize(self, input: str) -> str: ...
    def matches(self, a: str, b: str) -> bool: ...
    def similarity(self, a: str, b: str) -> float: ...
    def __repr__(self) -> str: ...
